name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:ember

  test-no-lock:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Test
        run: yarn test:ember

  test-try:
    name: Compatibility
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-release
          - ember-default-with-jquery
          - ember-default-with-ember-bootstrap-v3
          - ember-default-with-ember-bootstrap-v4
          - ember-default-with-plain-html
          - ember-classic
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Test
        run: npx --no-install ember try:one ${{ matrix.scenario }}

  coverage:
    name: Coverage Report
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Generage Report
        run: |
          chmod +x coverage.sh
          ./coverage.sh default
          ./coverage.sh bs3
          ./coverage.sh bs4
          ./coverage.sh plain-html
          ./node_modules/.bin/lcov-result-merger "lcov-*.info" "lcov.info"
      - name: Publish report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./lcov.info"
